log:
  loglevel: info
dns:
  servers:
  - https+local://8.8.8.8/dns-query
inbounds:
- port: 61080
  protocol: vmess
  settings:
    clients:
    - id: uuid
  streamSettings:
    network: ws
    wsSettings:
      path: /uuid
  sniffing:
    enabled: true
outbounds:
- protocol: freedom
  settings:
    domainStrategy: UseIPv4
